### ISSUE TITLE
HTTP file extraction of application/octet-stream not working as expected

### ISSUE THREAD

**Issue by jihadinho** [xplico/xplico#1]
Hi,

I'm using xplico to extract HTTP files from a pcap of 1.1 GB. Inisde there is a file transfer of ~ 1 GB(iso image). 
```
root@jaja:~/work/xplico# xplico -m pcap -f ../pcap/bigcap.pcap
root@jaja:~/work/xplico# du -ch -d1
35M     ./tmp
80M     ./xdecode
114M    .
114M    total
```

This is what I get. I was expecting to see at least 1GB of data, but it seems that the parsing is not correct. I am using the default config.
Since it is an iso I configured exe and iso in tcp_grb_dig.cfg:

```
root@jaja:~/work/xplico# cat /opt/xplico/cfg/tcp_grb_dig.cfg
# TCP garbage dig
# type concatenate start2end  size_limit   header footer

art . n 150000 \x4a\x47\x04\x0e \xcf\xc7\xcb
art . n 150000 \x4a\x47\x03\x0e \xd0\xcb\x00\x00
gif . n 5000000 \x47\x49\x46\x38\x37\x61 \x00\x3b
gif . n 5000000 \x47\x49\x46\x38\x39\x61 \x00\x00\x3b
jpg . n 200000000 \xff\xd8\xff\xe0\x00\x10 \xff\xd9
jpg . n 200000000 \xff\xd8\xff\xe1 \xff\xd9
png . n 20000000 \x50\x4e\x47? \xff\xfc\xfd\xfe
iso . n 2000000000 \x61\x70\x70\x6c\x69\x63\x61\x74\x69\x6f\x6e\x2f\x78\x2d\x69\x73\x6f\x39\x36\x36\x30\x2d\x69\x6d\x61\x67\x65
exe . n 1500000000 \x61\x70\x70\x6c\x69\x63\x61\x74\x69\x6f\x6e\x2f\x6f\x63\x74\x65\x74\x2d\x73\x74\x72\x65\x61\x6d
#bmp . n 100000 BM??\x00\x00\x00
tif . n 200000000 \x49\x49\x2a\x00
tif . n 200000000 \x4D\x4D\x00\x2A
#avi . n 50000000 RIFF????AVI
#
#mpg . n 50000000 \x00\x00\x01\xba \x00\x00\x01\xb9
#mpg . n 50000000 \x00\x00\x01\xb3 \x00\x00\x01\xb7
#wav . n 200000 RIFF????WAVE
#ra . n 1000000 .RMF
#ra . n 1000000 \x2e\x72\x61\xfd
asf . n 8000000 \x30\x26\xB2\x75\x8E\x66\xCF\x11\xA6\xD9\x00\xAA\x00\x62\xCE\x6C
wmv . n 20000000 \x30\x26\xB2\x75\x8E\x66\xCF\x11\xA6\xD9\x00\xAA\x00\x62\xCE\x6C
wma . n 8000000 \x30\x26\xB2\x75 \x00\x00\x00\xFF
wma . n 8000000 \x30\x26\xB2\x75 \x52\x9A\x12\x46
#mp3 . n 8000000 \xFF\xFB??\x44\x00\x00
#mp3 . n 8000000 \x57\x41\x56\45 \x00\x00\xFF\
#mp3 . n 8000000 \xFF\xFB\xD0\ \xD1\x35\x51\xCC\
#mp3 . n 8000000 \x49\x44\x33\
#mp3 . n 8000000 \x4C\x41\x4D\x45\
#doc . n 10000000 \xd0\xcf\x11\xe0\xa1\xb1
#doc + n 10000000 \xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1\x00\x00 \xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1\x00\x00
#pst . n 500000000 \x21\x42\x4e\xa5\x6f\xb5\xa6
#ost . n 500000000 \x21\x42\x44\x4e
#dbx . n 10000000 \xcf\xad\x12\xfe\xc5\xfd\x74\x6f
#idx . n 10000000 \x4a\x4d\x46\x39
#mbx . n 10000000 \x4a\x4d\x46\x36
#wpc . n 1000000 ?WPC

pdf . n 15000000 %PDF #%EOF\x0d
#pdf + y 15000000 %PDF #%EOF\x0a
#
#rpm . n 1000000 \xed\xab  #to short to correctly find the file
zip . n 10000000 PK\x03\x04 \x3c\xac
#rar . n 10000000 Rar!  #to short to correctly find the file
java . n 1000000 \xca\xfe\xba\xbe
tgz . n 20000000 \x1f\x8b\x08\x08
7z . n 2147483648 \x37\x7a\xbc\xaf\x27\x1c
#ogg . n 15728640 x4fx67x67x53x00x02 x4fx67x67x53x00x02
#blend . n 1000000000 BLENDER_v ENDB
#mus . n 1000000000 ENIGMA\x20BINARY\x20FILE \x13\x00\x06\x00\x00\x00
#amr . n 65535 \#!AMR
```

The results are the same. Can you please help me understand what is wrong? Is there a way to parse big http files?

**Comment by gnlcosta** [comment]
Hi,
there are many hypotheses.

- bug
- TCP with packets lost
- TCP checksum error: Have you disabled the checksum verification? ./xplico -c config/xplico_cli_nc.cfg -m pcap -f ../pcap/bigcap.pcap

Can you give me the access, also using ssh (your server/machine), to the pcap file?

**Comment by jihadinho** [comment]
I cannot give acces to my machine. You may download the pcap from here:
https://www.xfile.ro/download/32fb51349ea0b807165e8458b1390e7b.html

**Comment by gnlcosta** [comment]
I understood the issue. It is related to your capture system (probe).
In your pcap file there are many TCP packets with checksum error. Xplico by default checks the TCP checksum for each packet and if the checksum is incorrect it discards the packet.
This behavior can be changed using a different configuration file for Xplico, where you can tell to xplico to don't check the checksum.
If you use the configuration file named xplico_cli_nc.cfg you can extract from your pcap a file (http body) with size 1007M
`./xplico -c config/xplico_cli_nc.cfg -m pcap -f 10.10.125.204_45684_172.23.23.26_3128_1453136799.pcap
`

**Comment by jihadinho** [comment]
Great. Now I understand the xplico_cli_nc.cfg . So in most of the cases this is the config to use. 
Still I have some more questions.  
1. In my case, the octet stream is saved as: http_rs_body_1457361827_0x7ffaa4004d60_2 . Can I make xplico save the file with it's original name from the HTTP request packet? (in this case it is ubuntu-14.04.3-desktop-amd64.iso) 
2. Does xplico use port independent detection? (detecting protocols on non-standard ports) . I can see that in the case of HTTP it does. Does it work for all protocols?

Thank you for your help

**Comment by gnlcosta** [comment]
> So in most of the cases this is the config to use. 
Yes, but it is much important to know why your capture has so much TCP packets error (checksum), because in the case of a real error (and so TCP  retransmission) xplico will give you a bad reconstruction.
About your question:
1. yes. You have to parse the http header request/response, that xplico extracts. The dispatcher that you are using is cli (dispatch/cli/cli.c), therefore this is the place to change the code.
2. yes. I don't remember if for all protocols, but this was the idea.

**Comment by jihadinho** [comment]
Got it. 
What about the maximum file size for a capture?
I am runnint xplico over a 17GB pcap and I get segmentation fault. Please find the core dump and tmp/ folder here: https://www.xfile.ro/download/095eccae1b6edfb5f1cf23c43a0a99b7.html

I am attaching here frame 47044 where the segfault is happening. 
[frame47044.txt](https://github.com/xplico/xplico/files/162914/frame47044.txt)

Can you please help with the root cause and how can I fix it?

**Comment by gnlcosta** [comment]
Hi,
you are sharing very sensible data (every person that uses Internet now can access them). Please remove the file in xfile!
In your log there is a file named oops_xplico_178_1457430554.xml . Open this file and rename the pcap file with its absolute path, i.e.:
`<value>../pcap/roho_ro.pcap</value>`
to
`<value>absolute path</value>`
After that, from the source code dir of xplico launch:
`system/script/xml2pcap.php oops_xplico_178_1457430554.xml /tmp/bug.pcap`
and send me this pcap file (/tmp/bug.pcap)

About maximum files size: there is not limit (only file-system or HD size). You can produce also many pcap files and Xplico concatenates the flows/streams which start from a pcap and end in another.

**Comment by jihadinho** [comment]
OK. I understand the procedure. But I have deleted the files, so I will need to reproduce the issue. 

Please let's close this issue since it is related to HTTP file extraction. I will open a new issue for segfault with all the details.
