### ISSUE TITLE
Many corrupted and missing files with the http dissector

### ISSUE THREAD

**Issue by radare** [xplico/xplico#10]
Just did a simple pcap by doing some plain http browsing, then running xplico like this:
```
./xplico -m pcap -f dump.pcap
```

the `xdecode` directory is created and the contents are not what i expected..

* no css/js/html files in there
* all images are corrupted (some can be partly decoded)

this is not what i was expecting from the http extractor. is xplico really doing the tcp flow streams and gunzipping whats inside the HTTP communications?

**Comment by gnlcosta** [comment]
Yes, but it depends by many factors, for example:

- how the flows were captured
- if the flows have all packets
- if there is tcp packets with checksum error

If you send me the pcap I can say you why Xplico wasn't able to decode it...may be also bugs.

**Comment by radare** [comment]
I recorded the pcap with `tcpdump -s0 -w dump.pcap -n -i eno1`

**Comment by gnlcosta** [comment]
Ok, this can be not sufficient. Try disabling the checksum verification on Xplico: see configuration file named xplico_cli_nc.cfg

**Comment by radare** [comment]
Yay! That config works as expected! Thanks! Is this because i should be capturing with different flags?

**Comment by radare** [comment]
-K?

**Comment by gnlcosta** [comment]
it is likely that the issue comes from here: https://wiki.wireshark.org/CaptureSetup/Offloading
Normally this is the reason.
