### ISSUE TITLE
On live capturing, Xplico doesn't show system interfaces

### ISSUE THREAD

**Issue by M0Rf30** [xplico/xplico#15]
![senzanome](https://cloud.githubusercontent.com/assets/491117/21720752/2c712056-d425-11e6-88c7-3667dcf499d1.png)

**Comment by M0Rf30** [comment]
Could you try to use 
`ls /sys/class/net
`
in SolsController.php?

**Comment by gnlcosta** [comment]
Ok. Nice idea.

**Comment by M0Rf30** [comment]
not it works, but counters are not incremented. how to verify the correct acquisition?

**Comment by gnlcosta** [comment]
In the counters (start-date and stop-date I suppose) there was a bug (old bug).
About stop button, I'm not able to reproduce the issue.
