### ISSUE TITLE
`missing symbol in dis_tcp_grb`

### ISSUE THREAD

**Issue by radare** [xplico/xplico#8]
11:12:21 [CORE]{c}-ERROR: Can't load module modules/dis_tcp_grb.so: undefined symbol: ndpi_protocol2name
11:12:21 [CORE]{c}-FATAL: Load modules failed

**Comment by radare** [comment]
Same happens with `dis_udp_grb`

**Comment by radare** [comment]
Fixed by statically linking to libndpi and using RTLD_LAZY instead of RTLD_NOW in all the dlopens

**Comment by gnlcosta** [comment]
Thanks. It has been added.

**Comment by r4hul0** [comment]
@radare I am trying to run xplico and still I get this error : 

`13:52:56 [CORE]{c}-ERROR: Can't load module /opt/xplico/bin/modules/dis_tcp_grb.so: undefined symbol: ndpi_detection_get_sizeof_ndpi_id_struct
13:52:56 [CORE]{c}-FATAL: Load modules failed
`
I would very much be grateful if you could tell me how you fixed the error by statically linking the modules or how I could run xplico. Thanks ;)

**Comment by gcmitec** [comment]
Hi,
in /opt/xplico/config.. there is a configuration file, you have to remove the line:
MODULE=dis_udp_grb.so    LOG=FEWS

**Comment by r4hul0** [comment]
Thanks but that didn't help. I found /opt/xplico/cfg/xplico_cli.cfg where I commented the line you specified but nothing. How would I go about fixing it? I have very little knowledge of the workabouts of modules and c/c++ otherwise would have taken a look myself. Perhaps @radare could guide us :)
